version: '3.8'
services:
  webapp:
    build: .
    ports:
      - "7070:80"
    environment:
      - NODE_ENV=production
      - BASE_URL=http://localhost:7070
      - DEFAULT_ACCOUNT_LEVEL=epicinitiative
      - DB_CONNECTION_STRING=mongodb://mongoadmin:secret@mongo:27017
      - METRICS_DB_CONNECTION_STRING=mongodb://mongoadmin:secret@mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=improvedInit

    volumes:
      - mongodb_data:/data/db
#       - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    ports:
      - "27017:27017" # Optional: Expose this port only if you need to access the database from outside Docker.

volumes:
  mongodb_data: # This named volume will store the MongoDB data persistently
